name: Update Webpage Content

on:
  workflow_dispatch:  # Allows manual triggering via GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (adjust as needed)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch webpage content
        run: curl -o fmhy.txt https://api.fmhy.net/single-page # Replace URL and filename

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9  # Simplified commit action
        with:
          add: fmhy.txt  # File to commit
          message: 'Update webpage content'
          author_name: GitHub Actions
          author_email: actions@github.com
