name: Update Webpage Content

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit/push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch webpage content
        run: curl -s -o fmhy.txt https://api.fmhy.net/single-page || true

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: fmhy.txt
          message: "Update webpage content"
          author_name: GitHub Actions
